| /* confdefs.h.  */

#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define SP_MULTI_BYTE 1
#define SP_PACKAGE "OpenSP"
#define SP_VERSION "1.5.1"
#ifdef __cplusplus
#include <stdlib.h>
#endif
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_GETPAGESIZE 1
#define INTDIV0_RAISES_SIGFPE 1
#define HAVE_INTTYPES_H_WITH_UINTMAX 1
#define HAVE_STDINT_H_WITH_UINTMAX 1
#define HAVE_UNSIGNED_LONG_LONG 1
#define HAVE_INTTYPES_H 1
#define HAVE_ARGZ_H 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_NL_TYPES_H 1
#define HAVE_MALLOC_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_GETCWD 1
#define HAVE_GETEGID 1
#define HAVE_GETEUID 1
#define HAVE_GETGID 1
#define HAVE_GETUID 1
#define HAVE_MEMPCPY 1
#define HAVE_PUTENV 1
#define HAVE_SETENV 1
#define HAVE_SETLOCALE 1
#define HAVE_STPCPY 1
#define HAVE_STRCASECMP 1
#define HAVE_STRDUP 1
#define HAVE_STRTOUL 1
#define HAVE_TSEARCH 1
#define HAVE___ARGZ_COUNT 1
#define HAVE___ARGZ_STRINGIFY 1
#define HAVE___ARGZ_NEXT 1
#define HAVE_ICONV 1
#define ICONV_CONST const
#define HAVE_LC_MESSAGES 1
#define ENABLE_NLS 1
#define HAVE_LOCALE_H 1
#define SP_LOCALE_DIR "/usr/local/share/locale"
#define SP_MESSAGE_DOMAIN "sp4"
#define STDC_HEADERS 1
#define HAVE_LIMITS_H 1
#define HAVE_UNISTD_H 1
#define HAVE_IO_H 1
#define HAVE_NEW 1
#define HAVE_CASSERT 1
#define HAVE_STRUCT_STAT_ST_BLKSIZE 1
#define HAVE_ST_BLKSIZE 1
/* end confdefs.h.  */
